# Generated by Django 3.0 on 2019-12-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.Link')),
            ],
        ),
    ]
