# Generated by Django 3.0 on 2019-12-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='link',
        ),
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='robot.Category'),
        ),
    ]
