# Generated by Django 3.0 on 2019-12-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_auto_20191217_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
